### ISSUE TITLE
Random Questions

### ISSUE THREAD

**Issue by kleenkanteen** [PeterTYLiu/toaster#51]
1) What made you want to make this in the first place?

2) How many hours did it roughly take to make? And over how many weeks did you work on it?

3) What did you learn from making it?

**Comment by PeterTYLiu** [comment]
1. To see if it was possible!
2. Roughly 15-20 hrs over a few weekends to get a happy first draft
3. Learned best practices around the reducer/dispatch pattern and deeply nested state management.
